"""add fcm_token to users

Revision ID: 23190a6f23d6
Revises: 
Create Date: 2026-04-26 23:14:41.154993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23190a6f23d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
